### PR TITLE
Proposal: deterministically build a Phar

### PR DESCRIPTION
**Pull request by paragonie-scott**
This adds a .phar builder script that packages random_compat into a PHP Archive signed by an RSA key that I control, for which the corresponding public key is included in the `dist/` directory.

Questions:

1. Should this be merged?
2. Should we support self-updating? @padraic has done some work in this realm.
3. Does OpenSSL support ECDSA over NIST-P256?

### CODE REVIEW

**Comment by paragonie-scott** [comment]
Are github comments broken?

**Comment by glensc** [comment]
please do not store binaries to git. use github releases page to upload .phar and .phar.asc

but if you really must, exclude at least the /dist/ dir using .gitattributes! i do not wish to download library via composer and .phar as well.

**Comment by GrahamCampbell** [comment]
NB, you'll need to force push to remove the binary otherwise it's still there in git.

**Comment by glensc** [comment]
before force push:

rebase without binary being added in first place,
or just squash to one commit

**Comment by paragonie-scott** [comment]
That's a very good poing, @glensc. I'll be sure to rm then `rebase -i` and squash.

**Comment by glensc** [comment]
s/poing/point/ :D

**Comment by glensc** [comment]
aside, maybe you want to look at [box project](http://box-project.github.io/box2/) to build phar. not sure does it support adding filenames with different name, but if not, you could probably just add stub that requires the proper file.

**Comment by paragonie-scott** [comment]
Building / signing a Phar is actually quite trivial. I'd rather not depend on any more [pipe-shell](http://curlpipesh.tumblr.com/) projects if I can help it.

**Comment by paragonie-scott** [comment]
This is how I currently feel about the questions I posed a couple of months ago:

1. Should this be merged? **Yes.**
2. Should we support self-updating? **Probably not.**
3. Does OpenSSL support ECDSA over NIST-P256? **No, and RSA-2048 is probably OK until Ed25519 comes along.**

(Also, updated the PR.)

**Pull request merged**
