### PR TITLE
initial setup.

### PR DESCRIPTION
**Pull request by My1**
fix for #80

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
:-1:

**Comment by GrahamCampbell** [comment]
No way that's how it should be installed.

**Comment by My1** [comment]
then find a better way without using ALPHA software.

**Comment by oittaa** [comment]
As the README.md says:

**Do not use the master branch, use a [stable release](https://github.com/paragonie/random_compat/releases/latest).**

Then it's just `tar xzf  file.tar.gz` and in your PHP project `require_once('/path/to/lib/random.php');`
The documentation could be more clear about the file to be included though.

**Comment by rchouinard** [comment]
If you want to install the library by copying, that's on you. It's a horrible way to manage third-party dependencies these days, especially anything security related.

Composer is the current standard, and offers may advantages. I certainly wouldn't classify it as alpha software, it's production tested at a large scale. Composer isn't added to your application, and it doesn't go in your repository, so I'm not sure why LOC is an issue for you.

For a security library, it would be irresponsible to advocate installation using any other method, as Composer offers a clean way to track updates and keep the library up to date within consuming applications. Copy and paste is how we end up with outdated insecure code all over the place.

:-1: from me.

**Comment by paragonie-scott** [comment]
Sorry, I'll make the instructions clearer for non-composer users. I might even make a .phar builder and sign it.

**Comment by My1** [comment]
@oittaa I did use the files from stable. but there was no info about what needs to be done to finally get the lib working.

**Pull request closed without merging**
