### PR TITLE
Better test conditions for CAPICOM

### PR DESCRIPTION
**Pull request by paragonie-scott**
https://github.com/symfony/symfony/pull/16240#issuecomment-149036012

cc @nicolas-grekas - does this solve your Windows problems?

### CODE REVIEW

**Comment by nicolas-grekas** [comment]
Nope, but this should be easy to fix with the error message, which is:
`PHP Fatal error:  Uncaught exception 'com_exception' with message 'Failed to create COM object `CAPICOM.Utilities.1'`

**Comment by paragonie-scott** [comment]
How does that look?

**Comment by nicolas-grekas** [comment]
I'll check tomorrow, closing for today :)

**Comment by paragonie-scott** [comment]
Tested and confirmed on Windows.

**Pull request merged**
