### PR TITLE
Use libsodium for random bytes if it's available

### PR DESCRIPTION
**Pull request by cweagans**

### CODE REVIEW

**Comment by cweagans** [comment]
@paragonie-scott Any thoughts on this? I know you said applications would probably just use libsodium directly if available, but for applications that just call `random_bytes()` and use random_compat, it makes sense to me to use the best source of random bytes available.

**Comment by paragonie-scott** [comment]
To be honest, I'm conflicted.

On one hand: It's a great idea, it exposes a proactively secure CSPRNG just like PHP 7.0.0-RC5 will offer, and it's all around a great move.

On the other: because so few people installed it, I feel a bit silly about this. 

That's not a reason to not merge it, of course. But if we do, I'd also use `\Sodium\randombytes_uniform()` for `random_int()`.

Do @jedisct1 @ircmaxell or @narfbg have any thoughts?

**Comment by cweagans** [comment]
> I'd also use \Sodium\randombytes_uniform() for random_int().

Definitely. I wasn't sure how to get a random number from `randombytes_uniform()` with a lower boundary. That is, I can get 0 to whatever I pass to randombytes_uniform() (say 400), but I'm not sure how to get a random number between 100 and 400 without just getting multiple numbers and only returning the number if it's within that range - is that an okay approach?

**Comment by jedisct1** [comment]
It might not be a bad idea. In particular, it can allow to use `getrandom()`, thus work even if `/dev/urandom` is not available.

**Comment by jedisct1** [comment]
@cweagans `100 + randombytes_uniform(400-100)`?

**Comment by paragonie-scott** [comment]
I was actually going to write the uniform patch ;)

**Comment by paragonie-scott** [comment]
https://github.com/paragonie/random_compat/commit/be82e054a9cd17301754f8ee363fddf1bb5329bc

How does that look?

**Comment by cweagans** [comment]
:+1:

**Comment by jedisct1** [comment]
`\Sodium\randombytes_uniform($range) + $min` is not going to work if `$range` is more than `2147483647`, which can happen even on 32-bit platforms.

**Comment by paragonie-scott** [comment]
Sure, but in that case `$range` will be a `float`.

**Comment by paragonie-scott** [comment]
https://github.com/paragonie/random_compat/commit/9c78d5a12a2c97abd048f486224af9ae4a0ca90a

**Comment by jedisct1** [comment]
You can do better for the first call to `randombytes_uniform()` :)

**Comment by paragonie-scott** [comment]
You mean something like this?

```diff
-                $int |= \Sodium\randombytes_uniform(2147483647);
+                $int |= \Sodium\randombytes_uniform($range & 2147483647);
```

**Comment by paragonie-scott** [comment]
Oh wait derp. `>> 32`.

**Comment by jedisct1** [comment]
How about `$range >> 32` ?

**Comment by jedisct1** [comment]
Hahaha :)

**Comment by jedisct1** [comment]
Actually it would still be incorrect. You get 31 bits, not 32.

**Comment by paragonie-scott** [comment]
Does this look correct to you?
```php
$int = \Sodium\randombytes_uniform(($range >> 62) & 15); // 4 bits
$int <<= 4;
$int |= \Sodium\randombytes_uniform(($range >> 31) & 2147483647);
$int <<= 31;
$int |= \Sodium\randombytes_uniform($range & 2147483647);
$int += $min;
```

**Comment by paragonie-scott** [comment]
This might be more correct, since PHP doesn't have unsigned ints:
```php
$int = \Sodium\randombytes_uniform(($range >> 63) & 1); // 1 bit
$int |= 2; // We default to positive
# [ XX______ ________ ________ ________ ________ ________ ________ ________]

$int <<= 2;
$int |= \Sodium\randombytes_uniform(($range >> 31) & 2147483647);
$int <<= 31;
# [ XXYYYYYY YYYYYYYY YYYYYYYY YYYYYYYY Y_______ ________ ________ ________]

$int |= \Sodium\randombytes_uniform($range & 2147483647);
# [ XXYYYYYY YYYYYYYY YYYYYYYY YYYYYYYY YZZZZZZZ ZZZZZZZZ ZZZZZZZZ ZZZZZZZZ]
$int += $min;
```

**Comment by paragonie-scott** [comment]
https://github.com/paragonie/random_compat/commit/189687262346bde6a7f934643a9cbe3fc52aa93c

**Comment by jedisct1** [comment]
The ranges don't look correct.

Hold on, I'm installing php on this laptop in order to try something.

**Comment by jedisct1** [comment]
How about something like:
```php
$range0 = $range;
while ($range0 > 0) {
    $range0 >>= 1;
    $bits++;
}
do {
    $bits0 = $bits;
    $r = \Sodium\randombytes_uniform 0x40000000);
    $mask = 0x3fffffff >> (30 - min($bits0, 30));
    $int = ($r & $mask);
    $bits0 -= min(30, $bits0);

    $r = \Sodium\randombytes_uniform 0x40000000);
    $mask = 0x3fffffff >> (30 - min($bits0, 30));
    $int |= ($r & $mask) << 30;
    $bits0 -= min(30, $bits0);

    $r = \Sodium\randombytes_uniform 0x40000000);
    $mask = 0x3fffffff >> (30 - min($bits0, 30));
    $int |= ($r & $mask) << 60;
} while ($int > $range);
```
?

**Comment by jedisct1** [comment]
How about something like:
```php
$range0 = $range;
$bits0 = 0;

while ($range > 0) {
    $range >>= 1;
    $bits0++;
}

do {
    $bits = $bits0;
    $r = \Sodium\randombytes_uniform(0x40000000);
    $bits_comp = min($bits, 30);
    $mask = 0x3fffffff >> (30 - $bits_comp);
    $int = ($r & $mask);
    $bits -= $bits_comp;

    $r = \Sodium\randombytes_uniform(0x40000000);
    $bits_comp = min($bits, 30);
    $mask = 0x3fffffff >> (30 - $bits_comp);
    $int |= ($r & $mask) << 30;
    $bits -= $bits_comp;

    $r = \Sodium\randombytes_uniform(0x40000000);
    $mask = 0x3fffffff >> (30 - $bits);
    $int |= ($r & $mask) << 60;
} while ($int > $range0);

$int += $min;
```
?

**Comment by scottchiefbaker** [comment]
I've never even heard of libsodium until you mentioned, so I'll point out I have no dog in this fight. To put it simply, what are the pros and cons of doing this? I guess more importantly what are the cons?

We're potentially going to have an additional call to `is_function()` to check for libsodium before we actually return any data?

**Comment by paragonie-scott** [comment]
We have an additional `if (extension_loaded('libsodium'))` call, to be specific.

**Comment by paragonie-scott** [comment]
I opened #50 to discuss a 1.0.6 release. Please let me know if I made any mistakes since 1.0.5 that I'm oblivious to. :)

**Pull request merged**
