### PR TITLE
Fix require path for windows

### PR DESCRIPTION
**Pull request by wezzy**
In windows the generated path has the last separator wrong, using default PHP constant DIRECTORY_SEPARATOR allows your code to work correctly in both windows and *nix

### CODE REVIEW

**Comment by narfbg** [comment]
Just so it's noted - the forward slash does work perfectly well on Windows in PHP and there's nothing wrong with using it. I'm only aware of a single issue with it and it's in libxml.

But that being said, `DIRECTORY_SEPARATOR` is semantically more correct, so +1 from me.

**Comment by wezzy** [comment]
You are right, it should work but I don't know if this is due to a particular setup but we have lot of errors like this in out log:

[05-Jun-2018 19:39:55 Europe/Rome] PHP Fatal error:  require_once(): Failed opening required 'D:\Siti\project_name\vendor\paragonie\random_compat\lib/byte_safe_strings.php' (include_path='.;C:\php\pear') in D:\Siti\ricordavet.it\vendor\paragonie\random_compat\lib\random.php on line 52

Now that we changed to DIRECTORY_SEPARATOR in our local version those errors are gone

**Comment by pxgamer** [comment]
That is pretty weird as I've tested on Windows Server 2008, 2012 and 2016 and couldn't replicate this issue. But it's also mentioned in #136.

Anyway, this looks fine to me. 👍

**Comment by paragonie-scott** [comment]
There's no downside to this change, but as others have stated, I cannot reproduce this issue either.

**Comment by narfbg** [comment]
I'd bet the error state was cached ... That is, an include was attempted while the path didn't exist, PHP cached that it doesn't exist and then short-circuits on successive attempts, erroring while the path is now correct.

Changing the slash alters the path and therefore it no longer hits the cache, so that's why it looks like it's of any importance.

**Comment by paragonie-scott** [comment]
Oh hey that's new! Github didn't used to show comments on commits in this view before?

**Comment by glensc** [comment]
what is the "this view"? link? screenshot? :)

**Comment by paragonie-scott** [comment]
glensc0

```
  |
  v
```

gcal-02

**Comment by paragonie-scott** [comment]
glensc0

```
 |
 v
```
glensc1

**Comment by glensc** [comment]
i mean what's your url. i see your comment in PR view: https://github.com/paragonie/random_compat/pull/141#commitcomment-29381064

**Comment by paragonie-scott** [comment]
https://github.com/paragonie/random_compat/commit/8a6e54aafe79f145220ae011040404ed6de6dadc

**Comment by paragonie-scott** [comment]
The "that's new!" was about it also showing up in PR view.

**Comment by paragonie-scott** [comment]
Anyway, this is all off-topic.

1. I couldn't reproduce the issue.
2. The change was idempotent for anyone unaffected by the non-reproducible issue.
3. It apparently fixed the affected machines.
4. Commenting on commits rather than creating issues on GitHub [is bad](https://twitter.com/CiPHPerCoder/status/1007638291880054784).

**Pull request merged**
