### PR TITLE
Consolidate logic for wide ranges and narrow ranges

### PR DESCRIPTION
**Pull request by paragonie-scott**
See https://github.com/paragonie/random_compat/issues/11#issuecomment-120892665

I'd like to ask @CodesInChaos what they think of this suggested change?

### CODE REVIEW

**Comment by oittaa** [comment]
Seems like you didn't copy my suggested changes exactly and now you run quite easily to this: 
```
PHP Fatal error:  Uncaught exception 'Exception' with message 'random_int: RNG is broken - too many rejections' in random.php:248
```

For reference here's the file I made: http://pastebin.com/ZqGGByCM

**Comment by paragonie-scott** [comment]
Right. I was trying to replay a git diff manually.

**Comment by oittaa** [comment]
Yeah, I'm new to GitHub so I didn't know how to properly offer diff/patch here.

**Comment by paragonie-scott** [comment]
It's okay. If you click "edit" when viewing a script, it will create a fork (i.e. `paragonie/random_compat` -> `oittaa/random_compat`) that you can do whatever you want to. The Github way to send a patch upstream is to send a pull request. 

(I did something similar here, except between two different branches in the same repository rather than the "same" branch in two different repos.)

If you'd like to give it a try, I'll close this PR and let you issue one so the Github contributors tab will correctly give you credit for your contribution. (I still put everyone who contributes in the readme even if they don't trigger this mechanism.)

**Comment by paragonie-scott** [comment]
Obsoleted by #14

**Pull request closed without merging**
