### PR TITLE
Refacto to allow fine grained bootstrapping on PHP 5.3 and up

### PR DESCRIPTION
**Pull request by nicolas-grekas**
Diff may be best viewed ignoring whitespaces differences:
https://github.com/paragonie/random_compat/pull/74/files?w=1

This proposed changes refactorize the source so that implementations are separated from the bootstrapping logic:
- implementations are encapsulated in static classes so that they can be lazy-loaded using php autoloading
- PHP 5.2 compatibility is preserved: `require 'lib/random.php';` still works the same (no autoload required)
- when composer is used (ie on PHP5.3+), `lib/autoload.php` is used instead, which is a <10 lines bootstrapping script that is all what's required when no random_* function is used in a script
- thrown exceptions/errors now have the very same error message than the PHP7 ones,
- argument and result buffer validation is factorized in a single class (RandomBytes) so that each random source adapter doesn't have to care about that now,
- when possible, `isset()` is used in place of `strlen` so that the mbstring safe strlen is loaded only when really required

### CODE REVIEW

**Comment by narfbg** [comment]
-1024

None of this is necessary, it's just change for the sake of change. And especially the static class part - this package provides global functions, it *doesn't need* to use a class autoloader.

In addition we have already discussed the `isset()` vs `strlen()` thing and (although not explicitly) have agreed not to go that far with optimizations.

**Comment by nicolas-grekas** [comment]
Nothing is necessary. Except maybe the exception/error messages that should match PHP7's ones.
Is it useless?
I submitted this PR in the hope to make the code more readable, thus maintenable. I'd be happy to hear if someone else than me thinks I achieved this goal a bit.
I also submitted this PR for performance: instead of adding several require to the bootstrapping process, this refacto allows having a single very short one. Serious apps already have a bunch of things to do at bootstrapping, and I think that it's worth the optim, because things add up to measurable perf overheads.
I'd this package pretends to be the single canonical one for random_*() functions, I think it's worth it.

**Comment by narfbg** [comment]
To be fair, I didn't notice the exception messages' change - I like that one.

But other than that, what you seem to see as improvements, I see as the opposite. A change of style to your liking doesn't mean it's making it more readable or maintainable for everybody else.

I don't think this brings a performance improvement either ... all of these checks still have to be made one way or another. That one specific file now only has a single require doesn't mean anything. Did you benchmark it?

**Comment by paragonie-scott** [comment]
> Except maybe the exception/error messages that should match PHP7's ones.

Yeah, that's a really good point.

> I submitted this PR in the hope to make the code more readable, thus maintenable. I'd be happy to hear if someone else than me thinks I achieved this goal a bit.

It's a rather large change to take in, but I don't feel strongly about it one way or another.

> I don't think this brings a performance improvement either ... all of these checks still have to be made one way or another. That one specific file now only has a single require doesn't mean anything. Did you benchmark it?

I think @narfbg raises a good point here. I know BlackFire's *thing* is performance, so you're more likely to know performance hacks like the back of your hand. Could you show me what the performance impact of this PR would be?

**Comment by nicolas-grekas** [comment]
Back on this, I saw that you updated the exception message. I also extracted an additional test case and what I think is a cleanup of the .travis.yml file.
I tried to measure a perf delta with ab + php -S without success so far,
let's close this.

**Pull request closed without merging**
