### PR TITLE
Update random.php

### PR DESCRIPTION
**Pull request by lkobylski**
I want to add to open_basedir only '/dev/urandom' not all '/dev' directory.

### CODE REVIEW

**Comment by narfbg** [comment]
What you want to be able to do is OK, but effectively disabling open_basedir checks isn't the way to achieve it ...

@paragonie-scott 

I'd do this:

    $RandomCompatUrandom = (array() !== array_intersect(
        array('/dev', '/dev/', '/dev/urandom'),
        $RandomCompat_open_basedir
    ));

It also fixes a bug where if '/dev/' is part of open_basedir, it wouldn't be detected by random_compat because of the trailing slash.

**Comment by paragonie-scott** [comment]
I thought `open_basedir` could only be directories, not filenames.

**Comment by narfbg** [comment]
Well, it's one of those things that would require more code to limit it to just directories, so it doesn't make sense to exclude filepaths from it. :)
I'm pretty sure up until one point its values were even just a prefix that you could compare against with `strncmp()`.

**Comment by cs278** [comment]
> I thought open_basedir could only be directories, not filenames.

https://github.com/paragonie/random_compat/commit/144415fe86991730ac53e727abf3701b60295607#commitcomment-15764996

**Comment by paragonie-scott** [comment]
This should be resolved by v1.3.1 and v1.2.3

**Pull request closed without merging**
