### PR TITLE
Check mbstring.func_overload value rather than for existing functions.

### PR DESCRIPTION
**Pull request by twistor**
Check for the actual ini value rather than the mere existence of mb_* functions.

### CODE REVIEW

**Comment by narfbg** [comment]
This brings no benefit whatsoever ... the logic is such that it doesn't matter if *mbstring.func_overload* is enabled for string functions or not; it's just simpler to call the mbstring functions when they exist.

The current check is simpler and easier to understand IMO.

**Comment by twistor** [comment]
Well, there is a significant performance penalty to using mb_* 8bit versus native string functions.

**Comment by twistor** [comment]
My original patch had reduced this from 4 to 2 functions with a runtime check, but this seemed less invasive.

**Comment by narfbg** [comment]
I'm not aware of such a penalty and I usually do look for such things ... :) Do you benchmark the difference?

**Comment by twistor** [comment]
Rough calculations show mb_strlen() to be about %30 slower than strlen() and mb_substr() to be around %40 slower than substr().

Last time I did this, it was for filesystem work, so it may well be negligible.

**Comment by paragonie-scott** [comment]
Did these benchmarks specify 8bit?

**Comment by twistor** [comment]
https://gist.github.com/twistor/c0a74e951c607a763298

**Comment by narfbg** [comment]
You just wrote that and put as little effort in it as you could, didn't you? :)

But fair enough, mbstring functions do appear to be just a bit slower over 10m calls. IMO that's neglible for the purposes of this package, but personally I'd also take any optimization.

Which brings me to this crazy thought ... some `RandomCompat_strlen()` calls may be completely avoided by using `isset($string[$desiredLength - 1])` instead of `RandomCompat_strlen($string) === $desiredLength`.
That'd be ~5 times faster based on benchmarking `isset()` vs `strlen()` alone, surely even better when compared to `mb_strlen()` and not even considering the added overhead of calling a custom function.

It may be a bit too much however ... security should be the focus here, and readability is important in that context.

**Comment by paragonie-scott** [comment]
> security should be the focus here, and readability is important in that context.

Precisely. Making code review easy and simple, while providing the highest degree of security possible, is the goal of this library.

If our use of `mb_strlen()` is the bottleneck of any application, I offer my sincere congratulations to its developer.

Aside: Some attempts at micro-optimizing the library might in fact degrade security: For `random_int()`, we use a "discard and try again" if a random value falls outside the acceptable range. This allows us to guarantee a uniform distribution of the possible values. Someone might think they can cleverly reduce the number of random bytes fetched by replacing that with a modulo operator, but then they would have a biased RNG.

**Comment by redragonx** [comment]
Don't optimize until we need to or there's a demand for it.

**Comment by narfbg** [comment]
Well, my optimization would be perhaps too much, but if this one is changed to use the `MB_OVERLOAD_STRING` constant instead of the obscure value of `int(2)`, readability wouldn't be harmed IMO.

**Comment by paragonie-scott** [comment]
You've convinced me, @narfbg

**Pull request merged**
