### PR TITLE
Allow php 8 installation

### PR DESCRIPTION
**Pull request by BackEndTea**

### CODE REVIEW

**Comment by goba** [comment]
Looks good. Maybe to make it even more future proof for PHP 9, `>=7.0.0`? :) You never know how long will this package be around.

**Comment by BackEndTea** [comment]
I'd prefer to update it at that point, you never know what changes in PHP 9.0 😄. But if @paragonie-scott  prefers that i'll update it.

**Comment by goba** [comment]
What would cause problems with a no-op that has no code? ;)

**Review by andypost — APPROVED** [review]

**Comment by goba** [comment]
A quick update from the Drupal side. It turns out we are not impacted by this anymore as paragonie/random_compat does not show up as a dependency of any of our dependencies anymore when installing on PHP 7.4. That should be the same on PHP 8, so we are fine either way. Thanks again for this package bridging the gap while it was needed!

**Pull request merged**
