### PR TITLE
Add Github Issue Template

### PR DESCRIPTION
**Pull request by paragonie-scott**

### CODE REVIEW

**Comment by glensc** [comment]
what's the purpose? is it used automatically by github? can you include pointers?

not that it's any of my business, but why you create such low quality pull-requests? the whole PR could be omitted if you just commit to master if you're so lazy to write any explanation to the Pull Request.

**Comment by glensc** [comment]
found some doc meanwhile https://github.com/blog/2111-issue-and-pull-request-templates

**Comment by glensc** [comment]
but seems it does not work https://github.com/paragonie/random_compat/issues/new

**Comment by xabbuh** [comment]
@glensc This PR wasn't merged and it does not seem that these files have been added outside of this PR.

**Comment by paragonie-scott** [comment]
Yeah, I reconsidered this idea.

**Pull request closed without merging**
