### PR TITLE
random.php: unset $RandomCompatCOMtest

### PR DESCRIPTION
**Pull request by oittaa**

### CODE REVIEW

**Comment by narfbg** [comment]
I don't see the point in this in general, but if you want to clean-up temporary variables to avoid collisions, you could just do `$var = null;`.

`unset()` tries to free up memory immediately and that can be a bit slower at times, and superfluous since the garbage collector would try to do the same afterwards anyway. For all *functional* purposes, setting a regular variable to `null` has the same effect.

**Comment by oittaa** [comment]
Yeah, that's a possibility, but I tried to be consistent with the previously used variable handling.

**Comment by oittaa** [comment]
I ran some tests and couldn't see big differences in speed between ```unset($a)``` and ```$a = null```.

https://3v4l.org/7eIsg

**Comment by GrahamCampbell** [comment]
PHP 5.5 is showing it's about 60% slower. That's quite a big difference...

**Comment by oittaa** [comment]
And that's almost the maximum. We're not talking about 10x or 100x difference here.

**Comment by GrahamCampbell** [comment]
Yeh, sure, it's not no difference though.

**Comment by narfbg** [comment]
Yea, I didn't say it's a multiple-times difference, just that `unset()` is slower in general.

**Comment by paragonie-scott** [comment]
I'll consider setting them to `null` before 1.0.10.

**Pull request merged**
