### PR TITLE
Add composer install notice

### PR DESCRIPTION
**Pull request by bcremer**
This should give novice users a hint how to use this library.
See also issue #80 and PR #81.

### CODE REVIEW

**Comment by My1** [comment]
I would say let's add both because in the good old era of sharead hostong there's no way to run a bash.
also as seen here: https://getcomposer.org/download/ this thing is alpha, I wouldnt run alpha software on a server.

**Comment by narfbg** [comment]
You don't run it on production. You run it on your dev machine to automatically pull-in dependencies, but you'd still manually upload everything afterwards.

**Comment by My1** [comment]
well okay but what does composer do in case of this package?
if it isnt much you also could do this without any software, which makes it easier and alpha software isnt alpha and I dont wanna see my "dev machine" crash because of some weird software.
also composer probably messes with my php code when it creates requires or whatever at places where it might not even be needed (I have once central place where I get my random stuff and I dont need any includes at other spaces.

**Comment by narfbg** [comment]
I share your concerns about blindly trusting alpha-quality software, and to be fair - I don't like some things about Composer myself. However, when you say "it probably does something", it becomes quite clear that you're just looking for reasons to dismiss it.

I'll just say you'd be pleasantly surprised if you tried it.

**Comment by My1** [comment]
I dont want to dismiss it in general, I dont deny that it has its uses, but what I want is a way to do it without needing extra software. most "softwate" for PHP I tried just had a PHP I had to include and that's it.
also when composer adds the php library then it has to add the require/include directives somewhere, that's the logical conclusion. and I want to be the one who says where.

**Comment by smottt** [comment]
You, yourself, determine where you want to include the 'vendor/autoload.php' file which composer generates for you.

**Comment by My1** [comment]
so in the end it generates a file that I should include. okay. well as I said, I know next to nothing about composer and literally never used it.
I like doing the stuff manually, so I know what happens.

**Pull request closed without merging**
