### PR TITLE
Satisfies the php7.0 linter, fixes #115

### LINKED ISSUE #115: PHP linting problem when using PHP 7.
Some people want to write their code for a variety of systems, running a variety of PHP versions. This is exactly what this library is made for, to provide a backwards compatible way to generate random numbers.

However, if you do any kind of automatic linting to check for errors, then all the various random_bytes_* files will throw an error if you're using PHP 7 to do that linting. The specific error it will throw looks like this:

Fatal error: Cannot redeclare random_bytes() in .../random_compat/lib/random_bytes_com_dotnet.php on line 81.

..and similar.

Suggest that all these functions be wrapped in function_exists checks, or something equivalent, to prevent PHP 7's Lint process (php -l) from marking these as errors, even though they would not actually be used on a PHP 7 installation.

### PR DESCRIPTION
**Pull request by TortleWortle**

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
I don't see what this fixes?

**Comment by TortleWortle** [comment]
@GrahamCampbell The php7 linter prints an error if you lint all files this pr fixes that error.

**Comment by GrahamCampbell** [comment]
> @GrahamCampbell The php7 linter prints an error if you lint all files this pr fixes that error.

I don't think it does?

**Comment by GrahamCampbell** [comment]
You should not require those files

**Comment by TortleWortle** [comment]
@GrahamCampbell I am not requiring anything in my code however certain environments will lint every single php file.

**Comment by GrahamCampbell** [comment]
Sounds like the ide being broken then, rather.

**Comment by TortleWortle** [comment]
@GrahamCampbell In my case it's more like a server that is doing the checking.

**Comment by GrahamCampbell** [comment]
My point is rather that this library doesn't need to change, infact, it really shouldn't changed. These files were intentionally designed like this.

**Comment by TortleWortle** [comment]
@GrahamCampbell so people in this situation (including me) need to manually edit the code for the linter to work just because a few simple if statements is too much of a change?

**Comment by GrahamCampbell** [comment]
I'd recommend very far against editing the files.

I also wouldn't recommend closing this out before anyone else has voiced their opinion. :)

**Comment by TortleWortle** [comment]
@GrahamCampbell Well for my case I have to upload the vendor folder to a svn directory (wordpress) and they lint the php files and without editing the files manually in the vendor I cannot upload it.

and for the closing thing, I seem to have pressed the wrong button.

**Comment by GrahamCampbell** [comment]
Sounds like your host is "broken" to me.

**Comment by xabbuh** [comment]
@TortleWortle I have seen similar requests for the same reason (some kind of WordPress linter) on other repos where they have been rejected. The real solution imo would be to fix the tool so that it doesn't lint any third-party files at all (or being able to configure a pattern of files to exclude).

**Comment by TortleWortle** [comment]
@xabbuh Sadly we cannot do that.

**Comment by paragonie-scott** [comment]
Can you confirm if https://github.com/paragonie/random_compat/commit/1788eb294e9f2016045d6e2d202530b48d77671c (current `dev-master`) fixes the linter?

**Comment by paragonie-scott** [comment]
I'm going to close this PR due to merge conflicts introduced by independently adding if() checks that should prevent any code from being executed if your linter decides to inspect each individually. So, I believe, the issue is resolved.

If your linter is still complaining, I'm not sure what else we can do about it, but if you have any ideas, please feel free to open a new issue.

**Pull request closed without merging**
